/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.gui;

import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFormattedTextField;
import javax.swing.JFormattedTextField.AbstractFormatter;
import javax.swing.JFormattedTextField.AbstractFormatterFactory;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.autenticador.CredencialLoginSenha;
import model.cliente.Cliente;
import model.cliente.Endereco;
import view.Cliente_View;

/**
 *
 * @author rafael.cancian
 */
public class Cliente_View_Grafico extends javax.swing.JDialog implements Cliente_View {

    private Cliente model;

    /**
     * Creates new form Cliente_View_Grafico
     */
    public Cliente_View_Grafico(java.awt.Frame parent, boolean modal, Cliente model) {
        super(parent, modal);
        initComponents();
        formattedCPF.setFormatterFactory(new AbstractFormatterFactory() {
            @Override
            public AbstractFormatter getFormatter(JFormattedTextField jftf) {
                try {
                    return new MaskFormatter("###.###.###-##");
                } catch (ParseException ex) {
                    Logger.getLogger(Cliente_View_Grafico.class.getName()).log(Level.SEVERE, null, ex);
                }
                return null;
            }
        });
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacosGerais = new javax.swing.JPanel();
        labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        labelCPF = new javax.swing.JLabel();
        formattedCPF = new javax.swing.JFormattedTextField();
        panelEndereco = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textEndereco = new javax.swing.JTextArea();
        buttonSetEndereco = new javax.swing.JButton();
        panelBotoes = new javax.swing.JPanel();
        buttonCancela = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cliente");
        setModal(true);

        panelInformacosGerais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelNome.setText("Nome:");

        labelCPF.setText("CPF:");

        formattedCPF.setColumns(11);

        jLabel1.setText("Endereço:");

        textEndereco.setEditable(false);
        textEndereco.setColumns(20);
        textEndereco.setRows(6);
        jScrollPane1.setViewportView(textEndereco);

        buttonSetEndereco.setText("...");
        buttonSetEndereco.addActionListener(formListener);

        javax.swing.GroupLayout panelEnderecoLayout = new javax.swing.GroupLayout(panelEndereco);
        panelEndereco.setLayout(panelEnderecoLayout);
        panelEnderecoLayout.setHorizontalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSetEndereco)
                .addContainerGap())
        );
        panelEnderecoLayout.setVerticalGroup(
            panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnderecoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnderecoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonSetEndereco)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelInformacosGeraisLayout = new javax.swing.GroupLayout(panelInformacosGerais);
        panelInformacosGerais.setLayout(panelInformacosGeraisLayout);
        panelInformacosGeraisLayout.setHorizontalGroup(
            panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacosGeraisLayout.createSequentialGroup()
                        .addGroup(panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNome)
                            .addComponent(labelCPF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInformacosGeraisLayout.createSequentialGroup()
                                .addComponent(formattedCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textNome)))
                    .addComponent(panelEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInformacosGeraisLayout.setVerticalGroup(
            panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacosGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacosGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCPF)
                    .addComponent(formattedCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/gui/Bundle"); // NOI18N
        buttonCancela.setText(bundle.getString("CredencialLoginSenha_View_Grafico.buttonCancela.text")); // NOI18N
        buttonCancela.addActionListener(formListener);

        buttonOk.setText(bundle.getString("CredencialLoginSenha_View_Grafico.buttonOk.text")); // NOI18N
        buttonOk.addActionListener(formListener);

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                .addContainerGap(393, Short.MAX_VALUE)
                .addComponent(buttonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCancela)
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancela)
                    .addComponent(buttonOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInformacosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacosGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == buttonSetEndereco) {
                Cliente_View_Grafico.this.buttonSetEnderecoActionPerformed(evt);
            }
            else if (evt.getSource() == buttonCancela) {
                Cliente_View_Grafico.this.buttonOkActionPerformed(evt);
            }
            else if (evt.getSource() == buttonOk) {
                Cliente_View_Grafico.this.buttonCancelaActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelaActionPerformed
        model = null;
        setVisible(false);
    }//GEN-LAST:event_buttonCancelaActionPerformed

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        // TODO add your handling code here:
        String nome = textNome.getText();
        String cpf = formattedCPF.getText();
        if (nome.equals("")||cpf.equals("")) {
            JOptionPane.showMessageDialog(this, "Nome e CPF precisam ser definidos", "Cliente", JOptionPane.WARNING_MESSAGE);
        } else {
            model = new Cliente(cpf, nome, null);
            if (enderecoCliente != null) {
                model.addEndereco(enderecoCliente);
            }
            setVisible(false);
        }
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonSetEnderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSetEnderecoActionPerformed
        // TODO add your handling code here:
        Endereco_View_Grafico dialogo = new Endereco_View_Grafico(null, true, null);
        dialogo.setVisible(true);
        enderecoCliente = dialogo.getModel();
        if (enderecoCliente != null) {
            textEndereco.append("Estado: " + enderecoCliente.getEstado());
            textEndereco.append("\nCidade: " + enderecoCliente.getCidade());
            textEndereco.append("\nLogradouro: " + enderecoCliente.getLogradouro());
            textEndereco.append("\nNumero: " + enderecoCliente.getNumero());
            textEndereco.append("\nComplemento: " + enderecoCliente.getComplemento());
            textEndereco.append("\nCEP: " + enderecoCliente.getCep());
        }
    }//GEN-LAST:event_buttonSetEnderecoActionPerformed

    @Override
    public void mostre() {
        setVisible(true);
        
    }
    
    @Override
    public Cliente getModel() {
        return model;
    }

    private Endereco enderecoCliente;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancela;
    private javax.swing.JButton buttonOk;
    private javax.swing.JButton buttonSetEndereco;
    private javax.swing.JFormattedTextField formattedCPF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCPF;
    private javax.swing.JLabel labelNome;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelEndereco;
    private javax.swing.JPanel panelInformacosGerais;
    private javax.swing.JTextArea textEndereco;
    private javax.swing.JTextField textNome;
    // End of variables declaration//GEN-END:variables
}
