/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.gui;

import javax.swing.JOptionPane;
import model.autenticador.CredencialLoginSenha;
import model.autenticador.Credencial_if;
import view.Credencial_View;

/**
 *
 * @author rafaelcancian
 */
public class CredencialLoginSenha_View_Grafico extends javax.swing.JDialog implements Credencial_View {
    /**
     * Creates new form CredencialLoginSenha_View_Grafico
     */
    public CredencialLoginSenha_View_Grafico(java.awt.Frame parent, boolean modal, Credencial_if model) {
        super(parent, modal);
        this.model = model;
        initComponents();
        if (model==null) {
            this.textLogin.setText("");
            this.passwTextSenha.setText("");
        } else {
            CredencialLoginSenha modelLS = (CredencialLoginSenha) model;
            this.textLogin.setText(modelLS.getUsuario());
            this.passwTextSenha.setText(modelLS.getSenha());
        }
    }

    /**
     * Creates new form CredencialLoginSenha_View_Grafico
     */
    public CredencialLoginSenha_View_Grafico(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.model = null;
        initComponents();
        this.textLogin.setText("");
        this.passwTextSenha.setText("");
    }

    @Override
    public Credencial_if getModel() {
        return model;
    }

    @Override
    public void setCredencial() {
        setVisible(true);
    }

    private Credencial_if model;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelLogin = new javax.swing.JLabel();
        textLogin = new javax.swing.JTextField();
        labelSenha = new javax.swing.JLabel();
        passwTextSenha = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        buttonCancela = new javax.swing.JButton();
        buttonOk = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("view/gui/Bundle"); // NOI18N
        setTitle(bundle.getString("CredencialLoginSenha_View_Grafico.title")); // NOI18N
        setMaximumSize(new java.awt.Dimension(450, 200));
        setMinimumSize(new java.awt.Dimension(242, 110));
        setModal(true);
        setPreferredSize(new java.awt.Dimension(400, 150));
        setSize(new java.awt.Dimension(400, 150));

        labelLogin.setText(bundle.getString("CredencialLoginSenha_View_Grafico.labelLogin.text")); // NOI18N

        textLogin.setText(bundle.getString("CredencialLoginSenha_View_Grafico.textLogin.text")); // NOI18N

        labelSenha.setText(bundle.getString("CredencialLoginSenha_View_Grafico.labelSenha.text")); // NOI18N

        passwTextSenha.setText(bundle.getString("CredencialLoginSenha_View_Grafico.passwTextSenha.text")); // NOI18N

        buttonCancela.setText(bundle.getString("CredencialLoginSenha_View_Grafico.buttonCancela.text")); // NOI18N
        buttonCancela.addActionListener(formListener);

        buttonOk.setText(bundle.getString("CredencialLoginSenha_View_Grafico.buttonOk.text")); // NOI18N
        buttonOk.addActionListener(formListener);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(218, Short.MAX_VALUE)
                .addComponent(buttonOk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonCancela)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancela)
                    .addComponent(buttonOk))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSenha)
                            .addComponent(labelLogin))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textLogin)
                            .addComponent(passwTextSenha))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelLogin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelSenha)
                    .addComponent(passwTextSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName(bundle.getString("CredencialLoginSenha_View_Grafico.AccessibleContext.accessibleName")); // NOI18N

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == buttonCancela) {
                CredencialLoginSenha_View_Grafico.this.buttonCancelaActionPerformed(evt);
            }
            else if (evt.getSource() == buttonOk) {
                CredencialLoginSenha_View_Grafico.this.buttonOkActionPerformed(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void buttonOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonOkActionPerformed
        model = null;
        setVisible(false);
    }//GEN-LAST:event_buttonOkActionPerformed

    private void buttonCancelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelaActionPerformed
        String login = textLogin.getText();
        String senha = passwTextSenha.getText();//getPassword();
        if (login.equals("")||senha.equals("")) {
            JOptionPane.showMessageDialog(this, "Login e senha precisam ser definidos", "Credencial", JOptionPane.WARNING_MESSAGE);
        } else {
            model = new CredencialLoginSenha(login, senha);
            setVisible(false);
        }
    }//GEN-LAST:event_buttonCancelaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCancela;
    private javax.swing.JButton buttonOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelLogin;
    private javax.swing.JLabel labelSenha;
    private javax.swing.JPasswordField passwTextSenha;
    private javax.swing.JTextField textLogin;
    // End of variables declaration//GEN-END:variables
}
