/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.gui;

import java.text.ParseException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JFormattedTextField;
import javax.swing.ListModel;
import javax.swing.event.ListDataListener;
import javax.swing.text.MaskFormatter;
import model.cliente.Endereco;
import view.Endereco_View;

/**
 *
 * @author rafael.cancian
 */
public class Endereco_View_Grafico extends javax.swing.JDialog implements Endereco_View {

    /**
     * Creates new form Endereco_View_Grafico
     */
    public Endereco_View_Grafico(java.awt.Frame parent, boolean modal, Endereco model) {
        super(parent, modal);
        initComponents();
        formattedNumero.setFormatterFactory(new JFormattedTextField.AbstractFormatterFactory() {
            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField jftf) {
                try {
                    return new MaskFormatter("#####");
                } catch (ParseException ex) {
                    Logger.getLogger(Cliente_View_Grafico.class.getName()).log(Level.SEVERE, null, ex);
                }
                return null;
            }
        });
        formattedCEP.setFormatterFactory(new JFormattedTextField.AbstractFormatterFactory() {
            @Override
            public JFormattedTextField.AbstractFormatter getFormatter(JFormattedTextField jftf) {
                try {
                    return new MaskFormatter("#####-###");
                } catch (ParseException ex) {
                    Logger.getLogger(Cliente_View_Grafico.class.getName()).log(Level.SEVERE, null, ex);
                }
                return null;
            }
        });
        
        estadosCidades = new HashMap<>();
        estadosCidades.put("Rio Grande do Sul", new ArrayList<String>(Arrays.asList("POA", "PF", "BC")));
        estadosCidades.put("Santa Catarina", new ArrayList<String>(Arrays.asList("SJ", "FLN", "JVL")));
        
        ComboBoxModel<String> comboModel = new DefaultComboBoxModel<>();
        ((DefaultComboBoxModel) comboModel).addAll(estadosCidades.keySet());
        comboEstado.setModel(comboModel);
        listModel = new DefaultListModel();
        comboEstado.setSelectedItem("Rio Grande do Sul");
        listModel.addAll(estadosCidades.get(comboEstado.getSelectedItem()));
        listCidades.setModel(listModel);
        
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelInformacoesGerais = new javax.swing.JPanel();
        labelEstado = new javax.swing.JLabel();
        comboEstado = new javax.swing.JComboBox<>();
        labelCidade = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCidades = new javax.swing.JList<>();
        labelLogradouro = new javax.swing.JLabel();
        textLogradouro = new javax.swing.JTextField();
        labelComplemento = new javax.swing.JLabel();
        textComplemento = new javax.swing.JTextField();
        labelNumero = new javax.swing.JLabel();
        formattedNumero = new javax.swing.JFormattedTextField();
        labelCEP = new javax.swing.JLabel();
        formattedCEP = new javax.swing.JFormattedTextField();
        panelBotoes = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        btnCancela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelInformacoesGerais.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelEstado.setText("Estado:");

        comboEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboEstadoActionPerformed(evt);
            }
        });

        labelCidade.setText("Cidade:");

        jScrollPane1.setViewportView(listCidades);

        labelLogradouro.setText("Logradouro:");

        labelComplemento.setText("Complemento:");

        textComplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textComplementoActionPerformed(evt);
            }
        });

        labelNumero.setText("Numero:");

        formattedNumero.setColumns(5);
        try {
            formattedNumero.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        formattedNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedNumeroActionPerformed(evt);
            }
        });

        labelCEP.setText("CEP:");

        formattedCEP.setColumns(9);
        formattedCEP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formattedCEPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInformacoesGeraisLayout = new javax.swing.GroupLayout(panelInformacoesGerais);
        panelInformacoesGerais.setLayout(panelInformacoesGeraisLayout);
        panelInformacoesGeraisLayout.setHorizontalGroup(
            panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCidade)
                    .addComponent(labelEstado)
                    .addComponent(labelLogradouro)
                    .addComponent(labelComplemento)
                    .addComponent(labelNumero)
                    .addComponent(labelCEP))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textLogradouro)
                        .addComponent(textComplemento))
                    .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(formattedNumero, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(formattedCEP, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInformacoesGeraisLayout.setVerticalGroup(
            panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInformacoesGeraisLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEstado)
                    .addComponent(comboEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCidade)
                    .addGroup(panelInformacoesGeraisLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelLogradouro))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelComplemento)
                    .addComponent(textComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(formattedNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNumero))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInformacoesGeraisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCEP)
                    .addComponent(formattedCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnCancela.setText("Cancela");

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancela)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap())
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk)
                    .addComponent(btnCancela))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelInformacoesGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInformacoesGerais, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comboEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboEstadoActionPerformed
        listModel.clear();
        listModel.addAll(estadosCidades.get(comboEstado.getSelectedItem()));
        listCidades.setModel(listModel);
    }//GEN-LAST:event_comboEstadoActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        String estado = (String) comboEstado.getSelectedItem();
        String cidade = listCidades.getSelectedValue();
        String logradouro = textLogradouro.getText();
        int numero = Integer.parseInt(formattedNumero.getText());
        String complemento = textComplemento.getText();
        String cep = formattedCEP.getText();
        model = new Endereco(estado, cidade, logradouro, numero, complemento, cep);
        setVisible(false);
    }//GEN-LAST:event_btnOkActionPerformed

    private void formattedNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedNumeroActionPerformed

    private void textComplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textComplementoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textComplementoActionPerformed

    private void formattedCEPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formattedCEPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_formattedCEPActionPerformed

    @Override
    public void mostre() {
        setVisible(true);
    }
    
    @Override
    public Endereco getModel() {
        return model;
    }
    
    private Endereco model;
    private HashMap<String, ArrayList<String>> estadosCidades;
    private DefaultListModel listModel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancela;
    private javax.swing.JButton btnOk;
    private javax.swing.JComboBox<String> comboEstado;
    private javax.swing.JFormattedTextField formattedCEP;
    private javax.swing.JFormattedTextField formattedNumero;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCEP;
    private javax.swing.JLabel labelCidade;
    private javax.swing.JLabel labelComplemento;
    private javax.swing.JLabel labelEstado;
    private javax.swing.JLabel labelLogradouro;
    private javax.swing.JLabel labelNumero;
    private javax.swing.JList<String> listCidades;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JPanel panelInformacoesGerais;
    private javax.swing.JTextField textComplemento;
    private javax.swing.JTextField textLogradouro;
    // End of variables declaration//GEN-END:variables
}
