/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import javax.swing.JOptionPane;
import model.Fabrica;
import model.LivreMercado;
import model.autenticador.Autenticacao;
import model.autenticador.Credencial_if;
import model.fabrica.Fabrica_Grafica;
import view.Credencial_View;
import view.LivreMercado_View;

/**
 *
 * @author rafael.cancian
 */
public class LivreMercado_View_Grafico extends javax.swing.JFrame implements LivreMercado_View {

    /**
     * Creates new form NewJFrame
     *
     * @param model
     */
    public LivreMercado_View_Grafico(LivreMercado model) {
        initComponents();
        this.model = model;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelSplitPrincipal = new javax.swing.JSplitPane();
        painelScrollPrincipal = new javax.swing.JScrollPane();
        painelScrollEsquerdo = new javax.swing.JScrollPane();
        arvoreCategorias = new javax.swing.JTree();
        menuPrincipal = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LivreMercado");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        painelSplitPrincipal.setRightComponent(painelScrollPrincipal);

        arvoreCategorias.setPreferredSize(new java.awt.Dimension(150, 78));
        painelScrollEsquerdo.setViewportView(arvoreCategorias);

        painelSplitPrincipal.setLeftComponent(painelScrollEsquerdo);

        jMenu1.setText("File");
        menuPrincipal.add(jMenu1);

        jMenu2.setText("Edit");
        menuPrincipal.add(jMenu2);

        setJMenuBar(menuPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSplitPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 876, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelSplitPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                .addContainerGap())
        );

        getAccessibleContext().setAccessibleName("framePrincipal");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (model.getAutenticador().getAutenticacao()==null) {
            Credencial_View credencialView = ((Fabrica_Grafica) Fabrica.GetViewFabricaConcreta()).new_Credencial_View(this, true, null);
            credencialView.setCredencial();
            if (credencialView.getModel()==null) {
                //System.out.println("Sua credencial nao foi criada");
                JOptionPane.showMessageDialog(this, "Sua credencial nao foi criada", "Credencial", JOptionPane.WARNING_MESSAGE);
            } else {
                Credencial_if credencial = credencialView.getModel();
                Autenticacao autenticacao = model.getAutenticador().autentique_se(credencial);
                if (autenticacao==null) {
                    //System.out.println("Autenticacao falhou");
                    JOptionPane.showMessageDialog(this, "Autenticacao falhou", "Autenticacao", JOptionPane.WARNING_MESSAGE);
                } else {
                    //System.out.println("Voce se autenticou com sucesso");
                    JOptionPane.showMessageDialog(this, "Voce se autenticou com sucesso", "Autenticacao", JOptionPane.PLAIN_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_formWindowOpened

    @Override
    public void mostre() {
        setVisible(true);
    }

    private final LivreMercado model;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTree arvoreCategorias;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar menuPrincipal;
    private javax.swing.JScrollPane painelScrollEsquerdo;
    private javax.swing.JScrollPane painelScrollPrincipal;
    private javax.swing.JSplitPane painelSplitPrincipal;
    // End of variables declaration//GEN-END:variables
}
